version: "3.2" # because kompose conversion

services:

  championmodelserver:
    image: championmodelserver:1.0.0
    container_name: championmodelserver
    ports:
      - 8501:8501
      - 8500:8500

  scoreapp:
    image: scoreapp:1.0.0
    container_name: scoreapp
    ports:
      - 9999:9999
    depends_on:
      - championmodelserver
    volumes:
      - type: volume
        source: logs
        target: /log:z

  logger:
    image: logger:1.0.0
    container_name: logger
    ports:
      - 9998:9998
    depends_on:
      - scoreapp
      - championmodelserver
    volumes: #kompose does not support volumes_from
      - type: volume
        source: logs
        target: /log:z
    restart: always

  logdb:
    image: centos/postgresql-96-centos7 #postgres official docker image has some problem.
    container_name: logdb
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: ivnard
      POSTGRESQL_PASSWORD: developer
      POSTGRESQL_DATABASE: mydb
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  logs:
