version: "3.2" # because kompose conversion

services:

  score_server:
    image: pushed/champion_model
    container_name: tensorflow_server
    ports:
      - 8501:8501
      - 8500:8500

  score_app:
    image: pushed/score_app:1.0.0
    container_name: score_app
    ports:
      - 9999:9999
    depends_on:
      - score_server
    volumes:
      - type: volume
        source: logs
        target: /log

  logger:
    image: pushed/logger:1.0.0
    container_name: logger
    ports:
      - 9998:9998
    depends_on:
      - score_app
      - score_server
    volumes: #volume_from is not supported in kompose
      - type: volume
        source: logs
        target: /log

  logdb:
    image: pushed/postgres
    container_name: log_pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ivnard
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: mydb
    restart: always

  adminer:
    image: pushed/adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  logs: