apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: championmodelserver
  name: championmodelserver
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: championmodelserver:1.0.0
    generation: null
    importPolicy: {}
    name: 1.0.0
status:
  dockerImageRepository: ""
