connection:
    server: http://172.28.106.218 
    authUri: /SASLogon/oauth/token
    username: russasdemo  
    password: Orion123
endpoints:
    modelrepository_endpoint: /modelRepository/
modelrepository_meta:
    project_name: sas_modelops_tensorflow_openshift
server_meta:
    model_path: './model'
    model_artefact_name: 'champion_model.zip'
