data_meta:
    datapath_in: ./data/val/
    datapath_out: ./data/retrain/
variables_schema_meta:
    labels:
        - BAD
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC