data_meta:
    datapath: ../data
variables_schema_meta:
    target: BAD
    inputs:
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
    outputs:
        - P_BAD0
        - P_BAD1
        - EM_PROBABILITY
        - EM_CLASSIFICATION
model_endpoint_meta:
    schema: http
    ip: localhost #172.17.0.1
    port: 8501
    path: v1/models/model:classify
logging_meta:
    logpath: ../logs/
    prefix: OKDPERF
    timelabel: H
