variables_schema:
    target: BAD
    inputs:
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
    outputs:
        - P_BAD0
        - P_BAD1
        - EM_PROBABILITY
        - EM_CLASSIFICATION
model_endpoint:
    schema: http
    ip: localhost
    port: 8501
    path: v1/models/model:classify