logging_meta:
    #logfilepath: ./logs/log.csv
    logfilepath: /log/log.csv
table_meta:
    prefix: OKDPERF
    timelabel: H
db_endpoint_meta:
    driver: postgresql
    username: ivnard
    password: developer
    hostname: logdb #172.17.0.1 #localhost
    port: 5432
    dbname: mydb
