apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /home/ec2-user/kompose --provider openshift --file ../docker-compose.prod.yml
      -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    io.kompose.service: adminer
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
    spec:
      containers:
      - image: ' '
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - adminer
      from:
        kind: ImageStreamTag
        name: adminer:1.0.0
    type: ImageChange
status: {}
