apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/ec2-user/kompose --provider openshift --file /home/ec2-user/modelops-sas-tensorflow-workflow-manager-openshift/docker-compose.prod.yml
      -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: championmodelserver
  name: championmodelserver
spec:
  ports:
  - name: "8501"
    port: 8501
    targetPort: 8501
  - name: "8500"
    port: 8500
    targetPort: 8500
  selector:
    io.kompose.service: championmodelserver
status:
  loadBalancer: {}
