apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/ec2-user/kompose --provider openshift --file ../docker-compose.prod.yml
      -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logdb
  name: logdb
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: logdb
status:
  loadBalancer: {}
