apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /home/ec2-user/kompose --provider openshift --file ../docker-compose.prod.yml
      -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logdb
  name: logdb
spec:
  replicas: 1
  selector:
    io.kompose.service: logdb
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_PASSWORD
          value: developer
        - name: POSTGRES_USER
          value: ivnard
        image: ' '
        name: log-pgsql
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - log_pgsql
      from:
        kind: ImageStreamTag
        name: logdb:1.0.0
    type: ImageChange
status: {}
