apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: logdb
  name: logdb
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/postgres
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
