apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: logger
  name: logger
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: pushed/logger:1.0.0
    generation: null
    importPolicy: {}
    name: 1.0.0
status:
  dockerImageRepository: ""
