apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /home/ec2-user/kompose --provider openshift --file ../docker-compose.prod.yml
      -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scoreapp
  name: scoreapp
spec:
  replicas: 1
  selector:
    io.kompose.service: scoreapp
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: scoreapp
    spec:
      containers:
      - image: ' '
        name: scoreapp
        ports:
        - containerPort: 9999
        resources: {}
        volumeMounts:
        - mountPath: /log
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - scoreapp
      from:
        kind: ImageStreamTag
        name: scoreapp:1.0.0
    type: ImageChange
status: {}
