data_meta:
    datapath_in: '/opt/demos/modelops-sas-tensorflow-workflow-manager-openshift/data/val'
    datapath_out: '/opt/demos/modelops-sas-tensorflow-workflow-manager-openshift/data/retrain'
    datafile: 'retrain.csv'
variables_schema_meta:
    labels:
        - BAD
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
        - REASON
        - JOB
    target: BAD
    numerical_predictors:
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
    categorical_predictors:
        - REASON
        - JOB
labels_dict:
    REASON:
        - DebtCon
        - HomeImp
        - Missing
    JOB:
        - Other
        - Sales
        - ProfExe
        - Office
        - Mgr
        - Self
        - Missing
model_meta:
    learning_rate: 0.1
logs_dir: '/opt/demos/modelops-sas-tensorflow-workflow-manager-openshift/logs'



