data_meta:
    datapath_in: ./data/val
    datapath_out: ./data/retrain
    datafile: 'retrain.csv'
    test_size: 0.1
    random_state: 8
variables_schema_meta:
    labels:
        - BAD
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
        - REASON
        - JOB
    target: BAD
    numerical_predictors:
        - LOAN
        - MORTDUE
        - VALUE
        - YOJ
        - DEROG
        - DELINQ
        - CLAGE
        - NINQ
        - CLNO
        - DEBTINC
    categorical_predictors:
        - REASON
        - JOB
input_meta:
    mode: eval
    num_epochs: 2
    batch_size : 500
labels_dict:
    REASON:
        - DebtCon
        - HomeImp
        - Missing
    JOB:
        - Other
        - Sales
        - ProfExe
        - Office
        - Mgr
        - Self
        - Missing
model_meta:
    tf_random_seed: 8
    logs_dir: ./logs/tf_logs
    n_classes: 2
    batch_layer: 29
    lr: 0.1
    modelpath_out: ./models
    model_version: 2
    champion_path: ./models/champion
model_registration:
    metadata:
        outvar_names:
            - P_BAD0
            - P_BAD1
            - EM_CLASSIFICATION
            - EM_EVENTPROBABILITY
        labels:
            - 0
            - 1
        eventprob: 0.5
        projectname: sas_modelops_tensorflow_openshift
        modelname: Tensorflow_BoostedTreesClassifier
    registration:
        server: http://172.28.106.218
        username: russasdemo
        password: Orion123
        projectname: sas_modelops_tensorflow_openshift
        modelname: Tensorflow_BoostedTreesClassifier




